FEDERATION_SERVER = "https://stellereum-bridge.herokuapp.com/federation"

NODE_NAMES = [
"GDIR44J6EE3SVP4OAOAF7FAJGBXIHELRKHGC3RFAYXDE4I73S6ZNNW2F issuer",
]

ACCOUNTS = [
"$issuer"
]

[[CURRENCIES]]
code="ETH"
issuer="$issuer"
display_decimals=18
